/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__fpylll__interrupt__interrupt
#define __PYX_HAVE__fpylll__interrupt__interrupt


#ifndef __PYX_HAVE_API__fpylll__interrupt__interrupt

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(int) sig_raise_exception(int, char const *);

#endif /* !__PYX_HAVE_API__fpylll__interrupt__interrupt */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initinterrupt(void);
#else
PyMODINIT_FUNC PyInit_interrupt(void);
#endif

#endif /* !__PYX_HAVE__fpylll__interrupt__interrupt */
